# Generated by Django 5.0.4 on 2024-06-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_task_application_status_task_is_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='programming_language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
