# Generated by Django 5.0.4 on 2024-06-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_task_programming_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='programming_language',
        ),
        migrations.AddField(
            model_name='task',
            name='programming_languages',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='projects.programminglanguage'),
        ),
    ]
