# Generated by Django 5.0.4 on 2024-07-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskapplication',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
