version: '3.8'
services:
  appseed-app:
    container_name: appseed_app
    build: .
    volumes:
      - .:/app
      - ./home/static:/app/home/static 
      - ./media:/app/media             
    networks:
      - web_network

  nginx:
    container_name: nginx
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./home/static:/app/home/static  
      - ./media:/app/media              
    depends_on:
      - appseed-app
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
