# Generated by Django 5.0.7 on 2024-08-03 22:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wave_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Balance of Wave currency.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Wave Balance'),
        ),
    ]
